# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

bank = Bank.create(name: '707')
kick = Sound.create(bank: bank, name: '707 Kick 1', location: './assets/sounds/TR-707Kick01.wav')
Sound.create(bank: bank, name: '707 Snare 1', location: './assets/sounds/TR-707Snare01.wav')
Sound.create(bank: bank, name: '707 Hat Closed', location: './assets/sounds/TR-707Hat_C.wav')
Sound.create(bank: bank, name: '707 Hat Open', location: './assets/sounds/TR-707Hat_O.wav')
Sound.create(bank: bank, name: '707 Crash', location: './assets/sounds/TR-707Crash.wav')
Sound.create(bank: bank, name: '707 Ride', location: './assets/sounds/TR-707Ride.wav')
Sound.create(bank: bank, name: '707 Tom Hi', location: './assets/sounds/TR-707Tom_Hi.wav')
Sound.create(bank: bank, name: '707 Tom Mid', location: './assets/sounds/TR-707Tom_Mid.wav')
Sound.create(bank: bank, name: '707 Tom Lo', location: './assets/sounds/TR-707Tom_Lo.wav')

bank = Bank.create(name: '808')
Sound.create(bank: bank, name: '808 Kick 1', location: './assets/sounds/808/01.Bass.WAV')
Sound.create(bank: bank, name: '808 Snare 1', location: './assets/sounds/808/02.Snare.WAV')
Sound.create(bank: bank, name: '808 Hat Closed', location: './assets/sounds/808/03.ClosedHat.WAV')
Sound.create(bank: bank, name: '808 Hat Open', location: './assets/sounds/808/04.OpenHat.WAV')
Sound.create(bank: bank, name: '808 Crash', location: './assets/sounds/808/05.Crash.WAV')
Sound.create(bank: bank, name: '808 Ride', location: './assets/sounds/808/06.Ride.WAV')
Sound.create(bank: bank, name: '808 Tom Hi', location: './assets/sounds/808/07.Tom1.WAV')
Sound.create(bank: bank, name: '808 Tom Mid', location: './assets/sounds/808/08.Tom2.WAV')
Sound.create(bank: bank, name: '808 Tom Lo', location: './assets/sounds/808/09.Tom3.WAV')

bank = Bank.create(name: 'Acoustic Modern')
Sound.create(bank: bank, name: 'Acoustic Modern Kick 1', location: './assets/sounds/AcousticModern/01.Bass.WAV')
Sound.create(bank: bank, name: 'Acoustic Modern Snare 1', location: './assets/sounds/AcousticModern/02.Snare.WAV')
Sound.create(bank: bank, name: 'Acoustic Modern Hat Closed', location: './assets/sounds/AcousticModern/03.ClosedHat.WAV')
Sound.create(bank: bank, name: 'Acoustic Modern Hat Open', location: './assets/sounds/AcousticModern/04.OpenHat.WAV')
Sound.create(bank: bank, name: 'Acoustic Modern Crash', location: './assets/sounds/AcousticModern/05.Crash.WAV')
Sound.create(bank: bank, name: 'Acoustic Modern Ride', location: './assets/sounds/AcousticModern/06.Ride.WAV')
Sound.create(bank: bank, name: 'Acoustic Modern Tom Hi', location: './assets/sounds/AcousticModern/07.Tom1.WAV')
Sound.create(bank: bank, name: 'Acoustic Modern Tom Mid', location: './assets/sounds/AcousticModern/08.Tom2.WAV')
Sound.create(bank: bank, name: 'Acoustic Modern Tom Lo', location: './assets/sounds/AcousticModern/09.Tom3.WAV')

bank = Bank.create(name: 'Acoustic Vintage')
Sound.create(bank: bank, name: 'Acoustic Vintage Kick 1', location: './assets/sounds/AcousticVintage/01.Bass.WAV')
Sound.create(bank: bank, name: 'Acoustic Vintage Snare 1', location: './assets/sounds/AcousticVintage/02.Snare.WAV')
Sound.create(bank: bank, name: 'Acoustic Vintage Hat Closed', location: './assets/sounds/AcousticVintage/03.ClosedHat.WAV')
Sound.create(bank: bank, name: 'Acoustic Vintage Hat Open', location: './assets/sounds/AcousticVintage/04.OpenHat.WAV')
Sound.create(bank: bank, name: 'Acoustic Vintage Crash', location: './assets/sounds/AcousticVintage/05.Crash.WAV')
Sound.create(bank: bank, name: 'Acoustic Vintage Ride', location: './assets/sounds/AcousticVintage/06.Ride.WAV')
Sound.create(bank: bank, name: 'Acoustic Vintage Tom Hi', location: './assets/sounds/AcousticVintage/07.Tom1.WAV')
Sound.create(bank: bank, name: 'Acoustic Vintage Tom Mid', location: './assets/sounds/AcousticVintage/08.Tom2.WAV')
Sound.create(bank: bank, name: 'Acoustic Vintage Tom Lo', location: './assets/sounds/AcousticVintage/09.Tom3.WAV')

bank = Bank.create(name: 'Bass')
Sound.create(bank: bank, name: 'Bass E', location: './assets/sounds/Bass/01.E.WAV')
Sound.create(bank: bank, name: 'Bass F#', location: './assets/sounds/Bass/02.Fs.WAV')
Sound.create(bank: bank, name: 'Bass G', location: './assets/sounds/Bass/03.G.WAV')
Sound.create(bank: bank, name: 'Bass A', location: './assets/sounds/Bass/04.A.WAV')
Sound.create(bank: bank, name: 'Bass B', location: './assets/sounds/Bass/05.B.WAV')
Sound.create(bank: bank, name: 'Bass C', location: './assets/sounds/Bass/06.C.WAV')
Sound.create(bank: bank, name: 'Bass D', location: './assets/sounds/Bass/07.D.WAV')
Sound.create(bank: bank, name: 'Bass E2', location: './assets/sounds/Bass/08.E2.WAV')
Sound.create(bank: bank, name: 'Bass Fs2', location: './assets/sounds/Bass/09.Fs2.WAV')

bank = Bank.create(name: 'Bells')
Sound.create(bank: bank, name: 'Bells E', location: './assets/sounds/Bells/01.E.WAV')
Sound.create(bank: bank, name: 'Bells Fs', location: './assets/sounds/Bells/02.Fs.WAV')
Sound.create(bank: bank, name: 'Bells G', location: './assets/sounds/Bells/03.G.WAV')
Sound.create(bank: bank, name: 'Bells A', location: './assets/sounds/Bells/04.A.WAV')
Sound.create(bank: bank, name: 'Bells B', location: './assets/sounds/Bells/05.B.WAV')
Sound.create(bank: bank, name: 'Bells C', location: './assets/sounds/Bells/06.C.WAV')
Sound.create(bank: bank, name: 'Bells D', location: './assets/sounds/Bells/07.D.WAV')
Sound.create(bank: bank, name: 'Bells E2', location: './assets/sounds/Bells/08.E2.WAV')
Sound.create(bank: bank, name: 'Bells Fs2', location: './assets/sounds/Bells/09.Fs2.WAV')

bank = Bank.create(name: 'Marimba')
Sound.create(bank: bank, name: 'Marimba E', location: './assets/sounds/Marimba/01.E.WAV')
Sound.create(bank: bank, name: 'Marimba Fs', location: './assets/sounds/Marimba/02.Fs.WAV')
Sound.create(bank: bank, name: 'Marimba G', location: './assets/sounds/Marimba/03.G.WAV')
Sound.create(bank: bank, name: 'Marimba A', location: './assets/sounds/Marimba/04.A.WAV')
Sound.create(bank: bank, name: 'Marimba B', location: './assets/sounds/Marimba/05.B.WAV')
Sound.create(bank: bank, name: 'Marimba C', location: './assets/sounds/Marimba/06.C.WAV')
Sound.create(bank: bank, name: 'Marimba D', location: './assets/sounds/Marimba/07.D.WAV')
Sound.create(bank: bank, name: 'Marimba E2', location: './assets/sounds/Marimba/08.E2.WAV')
Sound.create(bank: bank, name: 'Marimba Fs2', location: './assets/sounds/Marimba/09.Fs2.WAV')

bank = Bank.create(name: 'Piano Chords')
Sound.create(bank: bank, name: 'Piano Chords E', location: './assets/sounds/Piano Chords/01.E.WAV')
Sound.create(bank: bank, name: 'Piano Chords Fs', location: './assets/sounds/Piano Chords/02.Fs.WAV')
Sound.create(bank: bank, name: 'Piano Chords G', location: './assets/sounds/Piano Chords/03.G.WAV')
Sound.create(bank: bank, name: 'Piano Chords A', location: './assets/sounds/Piano Chords/04.A.WAV')
Sound.create(bank: bank, name: 'Piano Chords B', location: './assets/sounds/Piano Chords/05.B.WAV')
Sound.create(bank: bank, name: 'Piano Chords C', location: './assets/sounds/Piano Chords/06.C.WAV')
Sound.create(bank: bank, name: 'Piano Chords D', location: './assets/sounds/Piano Chords/07.D.WAV')
Sound.create(bank: bank, name: 'Piano Chords E2', location: './assets/sounds/Piano Chords/08.E2.WAV')
Sound.create(bank: bank, name: 'Piano Chords Fs2', location: './assets/sounds/Piano Chords/09.Fs2.WAV')

bank = Bank.create(name: 'Piano High')
Sound.create(bank: bank, name: 'Piano High E', location: './assets/sounds/Piano High/01.E.WAV')
Sound.create(bank: bank, name: 'Piano High Fs', location: './assets/sounds/Piano High/02.Fs.WAV')
Sound.create(bank: bank, name: 'Piano High G', location: './assets/sounds/Piano High/03.G.WAV')
Sound.create(bank: bank, name: 'Piano High A', location: './assets/sounds/Piano High/04.A.WAV')
Sound.create(bank: bank, name: 'Piano High B', location: './assets/sounds/Piano High/05.B.WAV')
Sound.create(bank: bank, name: 'Piano High C', location: './assets/sounds/Piano High/06.C.WAV')
Sound.create(bank: bank, name: 'Piano High D', location: './assets/sounds/Piano High/07.D.WAV')
Sound.create(bank: bank, name: 'Piano High E2', location: './assets/sounds/Piano High/08.E2.WAV')
Sound.create(bank: bank, name: 'Piano High Fs2', location: './assets/sounds/Piano High/09.Fs2.WAV')

bank = Bank.create(name: 'Slap Bass')
Sound.create(bank: bank, name: 'Slap Bass E', location: './assets/sounds/Slap Bass/01.E.WAV')
Sound.create(bank: bank, name: 'Slap Bass Fs', location: './assets/sounds/Slap Bass/02.Fs.WAV')
Sound.create(bank: bank, name: 'Slap Bass G', location: './assets/sounds/Slap Bass/03.G.WAV')
Sound.create(bank: bank, name: 'Slap Bass A', location: './assets/sounds/Slap Bass/04.A.WAV')
Sound.create(bank: bank, name: 'Slap Bass B', location: './assets/sounds/Slap Bass/05.B.WAV')
Sound.create(bank: bank, name: 'Slap Bass C', location: './assets/sounds/Slap Bass/06.C.WAV')
Sound.create(bank: bank, name: 'Slap Bass D', location: './assets/sounds/Slap Bass/07.D.WAV')
Sound.create(bank: bank, name: 'Slap Bass E2', location: './assets/sounds/Slap Bass/08.E2.WAV')
Sound.create(bank: bank, name: 'Slap Bass Fs2', location: './assets/sounds/Slap Bass/09.Fs2.WAV')

bank = Bank.create(name: 'Synth Bass')
Sound.create(bank: bank, name: 'Synth Bass E', location: './assets/sounds/Synth Bass/01.E.WAV')
Sound.create(bank: bank, name: 'Synth Bass Fs', location: './assets/sounds/Synth Bass/02.Fs.WAV')
Sound.create(bank: bank, name: 'Synth Bass G', location: './assets/sounds/Synth Bass/03.G.WAV')
Sound.create(bank: bank, name: 'Synth Bass A', location: './assets/sounds/Synth Bass/04.A.WAV')
Sound.create(bank: bank, name: 'Synth Bass B', location: './assets/sounds/Synth Bass/05.B.WAV')
Sound.create(bank: bank, name: 'Synth Bass C', location: './assets/sounds/Synth Bass/06.C.WAV')
Sound.create(bank: bank, name: 'Synth Bass D', location: './assets/sounds/Synth Bass/07.D.WAV')
Sound.create(bank: bank, name: 'Synth Bass E2', location: './assets/sounds/Synth Bass/08.E2.WAV')
Sound.create(bank: bank, name: 'Synth Bass Fs2', location: './assets/sounds/Synth Bass/09.Fs2.WAV')

bank = Bank.create(name: 'Xylophone')
Sound.create(bank: bank, name: 'Xylophone E', location: './assets/sounds/Xylophone/01.E.WAV')
Sound.create(bank: bank, name: 'Xylophone Fs', location: './assets/sounds/Xylophone/02.Fs.WAV')
Sound.create(bank: bank, name: 'Xylophone G', location: './assets/sounds/Xylophone/03.G.WAV')
Sound.create(bank: bank, name: 'Xylophone A', location: './assets/sounds/Xylophone/04.A.WAV')
Sound.create(bank: bank, name: 'Xylophone B', location: './assets/sounds/Xylophone/05.B.WAV')
Sound.create(bank: bank, name: 'Xylophone C', location: './assets/sounds/Xylophone/06.C.WAV')
Sound.create(bank: bank, name: 'Xylophone D', location: './assets/sounds/Xylophone/07.D.WAV')
Sound.create(bank: bank, name: 'Xylophone E2', location: './assets/sounds/Xylophone/08.E2.WAV')
Sound.create(bank: bank, name: 'Xylophone Fs2', location: './assets/sounds/Xylophone/09.Fs2.WAV')

Sound.create(name: "Empty", location: './assets/sounds/808/10.Stop.WAV')
song = Song.create(title: 'Flatiron Blues', creator: 'Tom')
track = Track.create(song: song)

# TrackSound.create(track: track, sound: kick, position: 1)
# TrackSound.create(track: track, sound: kick, position: 3)
# TrackSound.create(track: track, sound: kick, position: 5)
# TrackSound.create(track: track, sound: kick, position: 7)
# TrackSound.create(track: track, sound: kick, position: 9)
# TrackSound.create(track: track, sound: kick, position: 11)
# TrackSound.create(track: track, sound: kick, position: 13)
# TrackSound.create(track: track, sound: kick, position: 15)